# Language-specific strings
de:
  title: Toolbox - School of Data CH
  tagline: Data Toolbox
  description: >
    Eine Sammlung von Open Source Tools empfohlen in der School of Data Schweiz
    f端r den Umgang mit offenen Daten. Wir bieten Unterst端tzung 端ber unser
    <a href="https://forum.schoolofdata.ch">Forum</a>
    und organisieren projektbasierte
    <a href="https://schoolofdata.ch">Workshops</a>.
  signup:
    title: Empfehlen
    name: Name
    email: E-mail
    comment: Nachricht
    skills: Empfohlenes Niveau ..
    beginner: Anfanger
    intermediate: Erfahrenen
    advanced: Profi
    expert: Experten
    send: Senden
  toolbox:
    categories:
      - name: define
        title: Define
        info: These tools can help to formulate good questions, which is key to finding good data.
      - name: find
        title: Find & Verify
        info: Often the same tool is used in both of these critical stages.
      - name: get
        title: Get
        info: Beyond downloads - collecting data through forms, mobile apps, web scraping and aggregation.
      - name: clean
        title: Clean
        info: Removing invalid entries, combining datasets, and doing any number of other normalizations.
      - name: analyse
        title: Analyse
        info: Machines can do a lot of it, but working with data will always involve analytical work.
      - name: present
        title: Present
        info: Data only has impact when it is packaged in an appropriate way for the audiences it needs to aim at
    tools:
      - categories: [ "find" ]
        name: opendata.swiss
        url: https://opendata.swiss/
        image: https://ogd.tg.ch/public/upload/assets/20/logo-kanton-thurgau.svg
        info: Der OGD-Ausschuss ist f端r die fachliche Steuerung der Umsetzung von OGD.
      - categories: [ "get" ]
        name: morph.io
        url: https://morph.io/documentation
      - categories: [ "clean" ]
        name: OpenRefine
        url: http://openrefine.org/

# Site links
title: School of Data Toolbox
url: "https://toolbox.schoolofdata.ch"
email: info@schoolofdata.ch
forum: "https://forum.schoolofdata.ch"
twitter: schoolofdata_ch
facebook: schoolofdata
github: schoolofdata-ch
grecaptcha:
  key: 6Lco8A8UAAAAAH68UXg94Ib9ptw6fRGxnZtSb0oQ

# Build settings
baseurl: "" # the subpath, e.g. /blog
markdown: kramdown
sass:
  sass_dir: sass

# Isotope settings
highlighter: rouge
exclude: [ minify.sh ]
