# Language-specific strings
de:
  title: Toolbox - School of Data
  tagline: School of Data [Toolbox]
  description: >
    Eine Sammlung von open source Tools empfohlen von der School of Data Schweiz für erfolgreichen Umgang mit offene Daten.
    Wir bieten weitere Unterstützung über <a href="https://forum.schoolofdata.ch">unser Forum</a>
    und organisieren projektbasierte <a href="https://schoolofdata.ch">Workshops</a>.
  signup:
    title: Tool Empfehlen
    header: Als ...
    myself: Person
    myorg: Organisation
    org: Firma/Schule
    name: Name
    email: E-mail
    comment: Nachricht
    skills: Empfohlenes Niveau ..
    beginner: Anfanger
    intermediate: Erfahrenen
    advanced: Profi
    expert: Experten
    send: Senden
  toolbox:
    categories:
      - name: extraction
        title: Extraction
        info: These tools help to find, identify, and collect data in one place.
    tools:
      - categories: [ extraction, portals ]
        name: OGD Kanton Thurgau
        url: https://ogd.tg.ch/
        image: https://ogd.tg.ch/public/upload/assets/20/logo-kanton-thurgau.svg
        info: Der OGD-Ausschuss ist für die fachliche Steuerung der Umsetzung von OGD im Kanton Thurgau zuständig. Er setzt sich zusammen aus Vertreter/innen datenpublizierender Ämter, dem e-Government-Koordinator sowie dem Datenschutzbeauftragten (beisitzend).

# Site links
title: School of Data Toolbox
url: "https://toolbox.schoolofdata.ch"
email: info@schoolofdata.ch
forum: "https://forum.schoolofdata.ch"
twitter: schoolofdata_ch
facebook: schoolofdata
github: schoolofdata-ch
grecaptcha:
  key: 6Lco8A8UAAAAAH68UXg94Ib9ptw6fRGxnZtSb0oQ

# Build settings
baseurl: "" # the subpath, e.g. /blog
markdown: kramdown
sass:
  sass_dir: sass

# Isotope settings
highlighter: rouge
exclude: [ minify.sh ]
